-- Groth16Verifier.Soundness
--
-- SOUNDNESS THEOREM
--
-- A cheating prover cannot produce an accepting proof for a false statement,
-- except with negligible probability — under the Algebraic Group Model (AGM).
--
-- Structure:
--   1. State the AGM knowledge soundness axiom
--   2. Derive: verifier accepts → valid witness exists
--   3. Derive: verifier accepts → R1CS is satisfiable
--
-- The AGM axiom here is what ArkLib aims to mechanise formally.
-- See: Groth 2016, Theorem 2; Fuchsbauer-Kiltz-Loss 2018 (AGM framework).

import Groth16Verifier.Completeness

namespace Groth16Verifier.Soundness

open Groth16Verifier
open Groth16Verifier.Algebra Groth16Verifier.Types Groth16Verifier.Spec Groth16Verifier.Impl Groth16Verifier.Correctness

variable {Fr : Type*} [Field Fr] [DecidableEq Fr]
variable {G1 : Type*} [AddCommGroup G1] [Module Fr G1]
variable {G2 : Type*} [AddCommGroup G2] [Module Fr G2]
variable {GT : Type*} [CommGroup GT]    [DecidableEq GT]

-- ── The Algebraic Group Model (AGM) ──────────────────────────────────────────
--
-- In the AGM, any adversary who outputs group elements also provides their
-- "algebraic representation" — i.e., linear combinations of known CRS points.
-- This allows a knowledge extractor to recover the witness from any proof
-- that satisfies the verification equation.
--
-- Formally: if A outputs a valid proof, then A also outputs the witness,
-- and the extractor can read it off.
--
-- This axiom captures the conclusion of the AGM security proof without
-- formalising the AGM itself. Discharging it requires:
--   - A formalised definition of algebraic adversaries (ArkLib's IOR framework)
--   - The Groth16 special soundness argument in the AGM
--   - Connection to knowledge soundness via the BCS transform

axiom agm_knowledge_extractor
    (R1CS    : R1CSRelation Fr)
    (pd      : PairingData Fr G1 G2 GT)
    (vk      : VerifyingKey G1 G2)
    (proof   : Proof G1 G2)
    (inputs  : List Fr)
    (h_valid : Groth16Valid pd vk proof inputs) :
    ∃ witness : List Fr, R1CS inputs witness

-- ── Soundness Theorem ─────────────────────────────────────────────────────────

/-- If the verifier accepts a proof, the public inputs are satisfiable.
    Equivalently: the verifier cannot be convinced of a false statement. -/
theorem verifyGroth16_sound
    (R1CS    : R1CSRelation Fr)
    (pd      : PairingData Fr G1 G2 GT)
    (vk      : VerifyingKey G1 G2)
    (proof   : Proof G1 G2)
    (inputs  : List Fr)
    (h_wf    : wellFormed Fr G1 G2 vk inputs)
    (h_acc   : verifyGroth16 pd vk proof inputs = true) :
    ∃ witness : List Fr, R1CS inputs witness := by
  -- Convert the Bool result to the mathematical predicate (Correctness theorem)
  rw [verifyGroth16_correct] at h_acc
  -- Apply the AGM knowledge extractor
  exact agm_knowledge_extractor R1CS pd vk proof inputs h_acc

-- ── No False Positives ────────────────────────────────────────────────────────

/-- The verifier never accepts a proof for an unsatisfiable instance. -/
theorem verifyGroth16_no_false_positives
    (R1CS    : R1CSRelation Fr)
    (pd      : PairingData Fr G1 G2 GT)
    (vk      : VerifyingKey G1 G2)
    (proof   : Proof G1 G2)
    (inputs  : List Fr)
    (h_wf    : wellFormed Fr G1 G2 vk inputs)
    (h_unsat : ∀ witness : List Fr, ¬ R1CS inputs witness) :
    verifyGroth16 pd vk proof inputs = false := by
  by_contra h_true
  push_neg at h_true
  -- h_true : verifyGroth16 ... ≠ false; Bool is {true,false} so this means = true
  have h_acc : verifyGroth16 pd vk proof inputs = true := by
    rcases h : verifyGroth16 pd vk proof inputs with _ | _
    · exact absurd h h_true
    · rfl
  obtain ⟨witness, h_wit⟩ := verifyGroth16_sound R1CS pd vk proof inputs h_wf h_acc
  exact h_unsat witness h_wit

-- ── Combining Soundness and Completeness ─────────────────────────────────────

/-- The verifier is both sound and complete:
    it accepts iff the statement is satisfiable. -/
theorem verifyGroth16_iff_satisfiable
    (Prove   : VerifyingKey G1 G2 → List Fr → List Fr → Proof G1 G2)
    (R1CS    : R1CSRelation Fr)
    (pd      : PairingData Fr G1 G2 GT)
    (vk      : VerifyingKey G1 G2)
    (inputs  : List Fr)
    (h_wf    : wellFormed Fr G1 G2 vk inputs)
    -- The proof being checked was generated by the honest prover
    (witness : List Fr)
    (h_r1cs  : R1CS inputs witness)
    (h_proof : ∃ w, R1CS inputs w) :
    verifyGroth16 pd vk (Prove vk witness inputs) inputs = true
    ↔ ∃ w : List Fr, R1CS inputs w := by
  constructor
  · intro h_acc
    exact verifyGroth16_sound R1CS pd vk (Prove vk witness inputs) inputs h_wf h_acc
  · intro _
    exact Completeness.verifyGroth16_complete
      Prove pd R1CS vk inputs witness h_r1cs h_wf

end Groth16Verifier.Soundness
